services:
  redis:
    image: redis:alpine
    restart: always
    hostname: cache-redis
    container_name: cache-redis
    ports:
      - '6377:6379'
    command: redis-server

  db:
    image: postgres:16
    container_name: postgres_16
    environment:
      POSTGRES_USER: botdatabase
      POSTGRES_PASSWORD: botdatabase
      POSTGRES_DB: botdatabase
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql

    networks:
      - db_network

  # mainbonbanh:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   command: python mainbonbanh.py
  #   restart: always
  #   volumes:
  #     - .:/app
  #   working_dir: /app
  #   depends_on:
  #     - redis

  # mainchotot:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   command: python mainchotot.py
  #   restart: always
  #   volumes:
  #     - .:/app
  #   working_dir: /app
  #   depends_on:
  #     - redis

volumes:
  db_data:

networks:
  db_network: