version: "2"
services:
  app:
    image: python:3.12.3
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "1704:8000"
    command: >
      sh -c "pip install -r requirements.txt && python mainbonbanh.py"
    restart: always

  app2:
    image: python:3.12.3
    working_dir: /app2
    volumes:
      - .:/app2
    ports:
      - "1706:8000"
    command: >
      sh -c "pip install -r requirements.txt && python mainchotot.py"
    restart: always

  postgres:
    image: postgres:16
    container_name: databaseTelegram
    environment:
      POSTGRES_USER: telebot
      POSTGRES_PASSWORD: telebot@123
      POSTGRES_DB: dbTelebot
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
      
volumes:
  postgres_data:

networks:
  bbsw-sport:
